-- ---------------- ROLES ----------------
INSERT INTO ROLES (ID, ROLE_NAME) VALUES (1, 'ADMIN');
INSERT INTO ROLES (ID, ROLE_NAME) VALUES (2, 'ANALYST');
INSERT INTO ROLES (ID, ROLE_NAME) VALUES (3, 'USER');

-- ---------------- USERS ----------------
INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, STATUS, ROLE_ID)
VALUES (1, 'Nanditha', 'Nanditha@test.com', '123', 'ACTIVE', 1);

INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, STATUS, ROLE_ID)
VALUES (2, 'Chandler', 'Chandler@test.com', '999', 'ACTIVE', 2);

INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, STATUS, ROLE_ID)
VALUES (3, 'Monica', 'Monica@test.com', '987', 'ACTIVE', 3);

INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, STATUS, ROLE_ID)
VALUES (4, 'Joy', 'Joy@test.com', '777', 'ACTIVE', 3);

INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, STATUS, ROLE_ID)
VALUES (5, 'Rose', 'Rose@test.com', '888', 'ACTIVE', 3);

-- ---------------- FINANCIAL RECORDS ----------------

-- Nanditha (ADMIN)
INSERT INTO FINANCIAL_RECORDS
(ID, AMOUNT, DATE, CATEGORY, DESCRIPTION, TYPE, USER_ID)
VALUES (1, 50000, '2026-04-05', 'Salary', 'Monthly salary', 'INCOME', 1);

INSERT INTO FINANCIAL_RECORDS
(ID, AMOUNT, DATE, CATEGORY, DESCRIPTION, TYPE, USER_ID)
VALUES (2, 1500, '2026-04-05', 'Food', 'Dinner', 'EXPENSE', 1);

INSERT INTO FINANCIAL_RECORDS
(ID, AMOUNT, DATE, CATEGORY, DESCRIPTION, TYPE, USER_ID)
VALUES (3, 3000, '2026-03-28', 'Travel', 'Taxi', 'EXPENSE', 1);

-- Chandler (ANALYST)
INSERT INTO FINANCIAL_RECORDS
(ID, AMOUNT, DATE, CATEGORY, DESCRIPTION, TYPE, USER_ID)
VALUES (4, 60000, '2026-04-01', 'Salary', 'April salary', 'INCOME', 2);

INSERT INTO FINANCIAL_RECORDS
(ID, AMOUNT, DATE, CATEGORY, DESCRIPTION, TYPE, USER_ID)
VALUES (5, 2000, '2026-04-02', 'Food', 'Lunch', 'EXPENSE', 2);

-- Monica (USER)
INSERT INTO FINANCIAL_RECORDS
(ID, AMOUNT, DATE, CATEGORY, DESCRIPTION, TYPE, USER_ID)
VALUES (6, 2500, '2026-04-03', 'Travel', 'Bus ticket', 'EXPENSE', 3);

INSERT INTO FINANCIAL_RECORDS
(ID, AMOUNT, DATE, CATEGORY, DESCRIPTION, TYPE, USER_ID)
VALUES (7, 1200, '2026-03-30', 'Food', 'Snacks', 'EXPENSE', 3);

-- Joy (USER)
INSERT INTO FINANCIAL_RECORDS
(ID, AMOUNT, DATE, CATEGORY, DESCRIPTION, TYPE, USER_ID)
VALUES (8, 1800, '2026-04-04', 'Food', 'Dinner', 'EXPENSE', 4);

-- Rose (USER)
INSERT INTO FINANCIAL_RECORDS
(ID, AMOUNT, DATE, CATEGORY, DESCRIPTION, TYPE, USER_ID)
VALUES (9, 2200, '2026-04-02', 'Travel', 'Train ticket', 'EXPENSE', 5);